#' createSiteTypeVector
#'
#' Creates a logical vector (0 = FALSE, 1 = TRUE) of whether a site belongs to a
#' given type. Used in economic analyses.
#'
#' @param graph_name (class igraph) the site contact network generated by the
#' script `03_CreateContactNetwork.R`
#' @param site_type (clas character) the site type to be assigned.
#'
#' @return (class vector) type_vector
#' @export
#'
#' @importFrom igraph vertex_attr
#'
createSiteTypeVector <- function(graph_name,
                                 site_type){
  site_category <- igraph::vertex_attr(graph = graph_name, name = site_type)
  type_vector <- ifelse(site_category == "N", 0, 1)
  return(type_vector)
}
